local LocalPlr = game.Players.LocalPlayer

--click
local ohString1 = "Click"

game:GetService("ReplicatedStorage").ClickEvent:FireServer(ohString1)
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

game:GetService("ReplicatedStorage").GameClient.Events.RemoteEvent.RebirthEvent:FireServer()
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "Reward3" -- 1 a 12

game:GetService("ReplicatedStorage").GameClient.Events.RemoteEvent.ClaimGift:FireServer(ohString1)

-- get best click
for _, v in pairs(game.ReplicatedStorage.Items.Pencil:GetDescendants()) do
	if v.Name == "PowerReq" then
		if LocalPlr.Rock.Value >= v.Value then 
			local PencilSelected = game:GetService("ReplicatedStorage").Items.Pencil[v.Parent.Parent.Name]
			game:GetService("ReplicatedStorage").GameClient.Events.RemoteEvent.ClickChangeEvent:FireServer(PencilSelected)
		end 
	end
end
-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide
game:GetService("ReplicatedStorage").GameClient.Events.RemoteEvent.SpaceEggEvent:FireServer()
game:GetService("ReplicatedStorage").GameClient.Events.RemoteEvent.FreePackEvent:FireServer()
game:GetService("ReplicatedStorage").GameClient.Events.RemoteEvent.EventEggEvent:FireServer()

-- This script was generated by Hydroxide's RemoteSpy: https://github.com/Upbolt/Hydroxide

local ohString1 = "2"

game:GetService("ReplicatedStorage").GameClient.Events.RemoteEvent.DailyEvent:FireServer(ohString1)
